services:
  php:
    build: .
    container_name: contact_manager_php
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:1.25-alpine
    container_name: contact_manager_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: contact_manager_db
    environment:
      MYSQL_DATABASE: contact_manager
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  database_data:
